version: 0.2

# AWS CodeBuild用のビルド設定ファイル
# Docusaurusを静的サイトとしてS3にデプロイします
# 
# 想定環境:
#   - プロジェクト名: hcredit
#   - 環境: poc
#   - S3バケット: hcredit-poc-web-content-703697785925
#   - リージョン: ap-northeast-1

env:
  variables:
    NODE_VERSION: "18"
    # ソースコードのディレクトリ（S3 sourceからの相対パス）
    DOCUSAURUS_DIR: "Docusaurus"
  # 以下は環境変数またはCodeBuildプロジェクト設定から注入
  # S3_BUCKET_NAME: "hcredit-poc-web-content-703697785925"
  # CLOUDFRONT_DISTRIBUTION_ID: ""（CloudFront作成後に設定）

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== Install Phase ==="
      - node --version
      - npm --version
      
  pre_build:
    commands:
      - echo "=== Pre-build Phase ==="
      - echo "Current directory: $(pwd)"
      - ls -la
      # Docusaurusディレクトリに移動して依存関係をインストール
      - cd ${DOCUSAURUS_DIR}
      - echo "Installing npm dependencies..."
      - npm ci --prefer-offline
      - echo "Dependencies installed successfully!"
  
  build:
    commands:
      - echo "=== Build Phase ==="
      - cd ${DOCUSAURUS_DIR}
      - echo "Building Docusaurus static site..."
      - npm run build
      - echo "Build completed successfully!"
      - ls -la build/
  
  post_build:
    commands:
      - echo "=== Post-build Phase ==="
      - cd ${CODEBUILD_SRC_DIR}
      # S3_BUCKET_NAMEが設定されている場合のみデプロイ
      # CloudFrontで /docs/* パスを使用するため、S3のdocs/ディレクトリにデプロイ
      - |
        if [ ! -z "${S3_BUCKET_NAME}" ]; then
          echo "Deploying to S3 bucket: ${S3_BUCKET_NAME}/docs/"
          aws s3 sync ${DOCUSAURUS_DIR}/build/ s3://${S3_BUCKET_NAME}/docs/ \
            --delete \
            --exclude ".git/*" \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "*.html" \
            --exclude "sitemap.xml" \
            --exclude "robots.txt"
          
          # HTMLファイルはキャッシュしない
          aws s3 sync ${DOCUSAURUS_DIR}/build/ s3://${S3_BUCKET_NAME}/docs/ \
            --exclude "*" \
            --include "*.html" \
            --include "sitemap.xml" \
            --include "robots.txt" \
            --cache-control "public, max-age=0, must-revalidate"
          
          echo "S3 deployment completed!"
        else
          echo "S3_BUCKET_NAME not set, skipping S3 deployment."
        fi
      
      # CloudFrontのキャッシュクリア（Distribution IDが設定されている場合のみ）
      - |
        if [ ! -z "${CLOUDFRONT_DISTRIBUTION_ID}" ] && [ "${CLOUDFRONT_DISTRIBUTION_ID}" != "None" ]; then
          echo "Invalidating CloudFront cache for distribution: ${CLOUDFRONT_DISTRIBUTION_ID}"
          aws cloudfront create-invalidation \
            --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
            --paths "/*"
          echo "CloudFront cache invalidation initiated!"
        else
          echo "CLOUDFRONT_DISTRIBUTION_ID not set, skipping cache invalidation."
        fi
      
      - echo "=== Deployment process completed! ==="

artifacts:
  files:
    - '**/*'
  base-directory: Docusaurus/build
  name: docusaurus-build-$(date +%Y%m%d-%H%M%S)
  discard-paths: no

cache:
  paths:
    - 'Docusaurus/node_modules/**/*'
    - '/root/.npm/**/*'
